### ISSUE TITLE
Add YAML validation and yamllint configuration

### ISSUE THREAD

**Issue by toshi0806** [smkwlab/sotsuron-template#56]
### Problem
GitHub Actions workflows must be validated before commits to prevent syntax errors and deployment failures. Currently, there's no systematic validation of YAML files in this repository.

#### 1. Add yamllint Configuration
Create `.yamllint.yml` with GitHub Actions optimized rules:

```yaml
---
# yamllint configuration for GitHub Actions workflows
extends: default

rules:
  # Allow truthy values like 'on:', 'true', 'yes' in GitHub Actions
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
    check-keys: false
  
  # Relax line length for readable workflow comments
  line-length:
    max: 120
    
  # Allow missing document start for simple files
  document-start:
    present: false
    
  # Be stricter about trailing spaces
  trailing-spaces: enable
  
  # Ensure proper indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
```

#### 2. Validation Commands
Add these validation steps to development workflow:

```bash
# Install tools
pip install yamllint
npm install -g @microsoft/action-github

# Validate YAML syntax
yamllint .github/workflows/*.yml

# Validate GitHub Actions specific syntax
actionlint .github/workflows/*.yml
```

#### 3. Pre-commit Validation
Ensure all workflow files are validated before commits.

### Current Workflow Files
This repository contains:
- `auto-final-merge.yml`
- `create-next-draft.yml`
- `latex-build.yml`
- `update-review-branch.yml`

### Benefits
- ✅ Prevent syntax errors in workflows
- ✅ Consistent YAML formatting across repository
- ✅ Automated validation prevents deployment failures
- ✅ Better maintainability of workflow files
- ✅ Critical for thesis review automation reliability

### Implementation Priority
**High** - Essential for maintaining automated thesis review system reliability.

### Related
Part of ecosystem-wide YAML validation initiative (see latex-template implementation).
